language: node_js

node_js: 12  # 要安装的node版本为当前的稳定版

cache:
  directories:
  - node_modules # 要缓存的文件夹

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:   # 最后执行的命令
  - cd ./public
  - git init
  - git config user.name "Jason210314"
  - git config user.email "wmc314@outlook.com"
  - git add . 
  - git commit -m "Update Blod by Travis CI"
  - git push --force --quiet "https://${GP_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - hexo # 触发持续集成的分支

env:
 global:
   - GH_REF: github.com/Jason210314/Jason210314.github.io.git