name: Deploy

on:
  push:
    branches:
      - hexo
  pull_request:
    branches:
      - hexo
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: 'hexo'

    - name: build
      run: |
        npm install
        hexo g
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}
        publish_dir: public